<?php

namespace Database\Seeders;

use App\Models\Animal;
use Illuminate\Database\Seeder;

class AnimalSeeder extends Seeder
{
    public function run(): void
    {
        $animals = [
            [
                'name' => 'Max',
                'species' => 'dog',
                'breed' => 'Berger Allemand',
                'age' => 3,
                'sex' => 'male',
                'description' => 'Chien affectueux et sportif, parfait pour une famille active.',
                'status' => 'available',
                'size' => 'large',
                'vaccinated' => true,
                'sterilized' => true,
                'health_status' => 'good',
                'photos' => ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e'],
            ],
            [
                'name' => 'Luna',
                'species' => 'cat',
                'breed' => 'Siamois',
                'age' => 2,
                'sex' => 'female',
                'description' => 'Chatte calme et sociable, adore les câlins.',
                'status' => 'available',
                'size' => 'medium',
                'vaccinated' => true,
                'sterilized' => false,
                'health_status' => 'good',
                'photos' => ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba'],
            ],
            [
                'name' => 'Rocky',
                'species' => 'dog',
                'breed' => 'Labrador',
                'age' => 5,
                'sex' => 'male',
                'description' => 'Gentil labrador très sociable avec les enfants.',
                'status' => 'available',
                'size' => 'large',
                'vaccinated' => true,
                'sterilized' => true,
                'health_status' => 'fair',
                'photos' => ['https://images.unsplash.com/photo-1552053831-71594a27632d'],
            ],
            [
                'name' => 'Milo',
                'species' => 'cat',
                'breed' => 'Européen',
                'age' => 1,
                'sex' => 'male',
                'description' => 'Jeune chat très joueur et curieux.',
                'status' => 'available',
                'size' => 'small',
                'vaccinated' => false,
                'sterilized' => false,
                'health_status' => 'good',
                'photos' => [],
            ],
            [
                'name' => 'Bella',
                'species' => 'dog',
                'breed' => 'Golden Retriever',
                'age' => 4,
                'sex' => 'female',
                'description' => 'Superbe golden très douce et obéissante.',
                'status' => 'adopted',
                'size' => 'large',
                'vaccinated' => true,
                'sterilized' => true,
                'health_status' => 'good',
                'photos' => ['https://images.unsplash.com/photo-1633722715463-d30f4f325e24'],
            ],
            [
                'name' => 'Nala',
                'species' => 'cat',
                'breed' => 'Maine Coon',
                'age' => 3,
                'sex' => 'female',
                'description' => 'Grande chatte majestueuse, très câline malgré sa taille.',
                'status' => 'available',
                'size' => 'large',
                'vaccinated' => true,
                'sterilized' => true,
                'health_status' => 'good',
                'photos' => ['https://images.unsplash.com/photo-1533738363-b7f9aef128ce'],
            ],
            [
                'name' => 'Rex',
                'species' => 'dog',
                'breed' => 'Boxer',
                'age' => 2,
                'sex' => 'male',
                'description' => 'Chien énergique et protecteur, idéal pour une maison avec jardin.',
                'status' => 'available',
                'size' => 'medium',
                'vaccinated' => true,
                'sterilized' => false,
                'health_status' => 'good',
                'photos' => ['https://images.unsplash.com/photo-1535930749574-1399327ce78f'],
            ],
            [
                'name' => 'Whiskers',
                'species' => 'cat',
                'breed' => 'Persan',
                'age' => 4,
                'sex' => 'male',
                'description' => 'Chat calme et posé, parfait pour un appartement tranquille.',
                'status' => 'in_care',
                'size' => 'medium',
                'vaccinated' => true,
                'sterilized' => true,
                'health_status' => 'fair',
                'photos' => ['https://images.unsplash.com/photo-1567270671170-fdc10a5bf831'],
            ],
            [
                'name' => 'Daisy',
                'species' => 'dog',
                'breed' => 'Beagle',
                'age' => 6,
                'sex' => 'female',
                'description' => 'Chienne douce et affectueuse, adore les promenades en forêt.',
                'status' => 'available',
                'size' => 'medium',
                'vaccinated' => true,
                'sterilized' => true,
                'health_status' => 'good',
                'photos' => ['https://images.unsplash.com/photo-1505628346881-b72b27e84530'],
            ],
            [
                'name' => 'Simba',
                'species' => 'cat',
                'breed' => 'Bengal',
                'age' => 1,
                'sex' => 'male',
                'description' => 'Chaton très actif et joueur, besoin de beaucoup d\'attention.',
                'status' => 'available',
                'size' => 'small',
                'vaccinated' => false,
                'sterilized' => false,
                'health_status' => 'good',
                'photos' => ['https://images.unsplash.com/photo-1513245543132-31f507417b26'],
            ],
        ];

        foreach ($animals as $animal) {
            Animal::create($animal);
        }
    }
}
